---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: ubuntu01
    box: ubuntu/jammy64
    memory: 1024
    cpus: 2
    provider_options:
      gui: false
    interfaces:
      - network_name: "vboxnet1"
        type: "hostonly"
        ip: "192.168.57.13"
    instance_raw_config_args:
      - "vm.network 'private_network', ip: '192.168.57.13'"
provisioner:
  name: ansible
  env:
    ANSIBLE_CACHE_PLUGIN: jsonfile
    ANSIBLE_CACHE_PLUGIN_CONNECTION: "cache/"
    ANSIBLE_HOST_KEY_CHECKING: "false"
  inventory:
    group_vars:
      docker_k8s_cluster:
        lb_vip: "192.168.57.13"
        listen_nic: "enp0s8"
  config_options:
    defaults:
      interpreter_python: auto
      callback_whitelist: profile_tasks
      timeout: 30
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
verifier:
  name: ansible
