---

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu01
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true
    groups:
      - docker_haproxy
  - name: ubuntu02
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true
    groups:
      - docker_haproxy

provisioner:
  name: ansible
  env:
    ANSIBLE_CACHE_PLUGIN: jsonfile
    ANSIBLE_CACHE_PLUGIN_CONNECTION: "cache/"
  inventory:
    group_vars:
      docker_haproxy:
        k8s_api_ips: ["172.17.0.10","172.17.0.11","172.17.0.12",]
        lb_vip: "172.17.0.100"
        listen_nic: "eth0"

scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy

...
