---

- name: Restart kubelet
  become: yes
  ansible.builtin.systemd:
    name: kubelet
    state: restarted

- name: Start containerd
  become: yes
  ansible.builtin.systemd:
    name: containerd
    state: started

- name: Restart containerd
  become: yes
  ansible.builtin.systemd:
    name: containerd
    state: restarted

...
