---

- name: Restart kubelet
  become: yes
  ansible.builtin.systemd:
    name: kubelet
    state: restarted

- name: Restart containerd        
  become: yes
  ansible.builtin.systemd:
    name: containerd
    state: restarted

...
