---

#### disable apparmor
- name: Stop apparmor service
  become: yes
  ansible.builtin.systemd:
    name: apparmor
    state: stopped

- name: Disable apparmor service
  become: yes
  ansible.builtin.systemd:
    name: apparmor
    enabled: no


#### force systemd cgroup usage 
- name: Render containerd/config.toml.2 template
  become: yes
  template:
    src: containerd/config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  notify: Restart containerd

...
